# This method looks for what's specified in the Dockerfile
version: "3.0"
services:
  meta-framework:
    build:
      context: .
      dockerfile: Dockerfile-part1
      target: next-graphql
    ports:
      - "3102:3102"
  frontend-only:
    build:
      context: .
      dockerfile: Dockerfile-part1
      target: react-vite
    ports:
      - "5173:5173"
