version: "3.0"
services:
  meta-framework:
    image: nextgraphql:22-bookworm-slim
    ports:
      - "3102:3102"
    volumes:
      - ./:/home/node/
  frontend-only:
    image: react-vite:22-bookworm-slim
    ports:
      - "5173:5173"
    volumes:
      - ./:/home/node/
